version: "3.9"

services:
  unzipbot:
    build: .
    container_name: unzipbot
    restart: always
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - API_ID=${API_ID}
      - API_HASH=${API_HASH}
    volumes:
      - .:/app
    command: python bot.py
